# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39e159b1bc4862358020673b8dc4ed822d59852f5535e1c6291a8dd3639fffc56f034476a5c468a8fefce6e96556cac0996c0e5274a7e5c0ee8c828f77afe4ce

test:
  secret_key_base: 184011d7eedecb1f746edc0090316bbe3025b7ab44b52d9323fd2b98dfeb6aad6c4d3fda996d607c7da2e7e3b6c1de7a085617e5f928a2e536356df94a78e297

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
